### ISSUE TITLE
Fix the math to work with arbitrary templates

### ISSUE THREAD

**Issue by aud-tree** [traa-pixelcanvas/PixelCanvasBot#1]
As of now, templates must align along a 15x15 block grid (960x960px). The code doesn't handle that, so we've compensated by using templates that center on a grid intersection.

Change the math so that the canvas is read at block grid intersections in a way that allows for templates of any size at any location.

Work on this is being done on the `maths` branch.

**Comment by Mismatchia** [comment]
As of 4296ab22069604f417b1c4ebce73f2804c6e500d, this issue appears to be solved! Great work :)
